local wezterm = require("wezterm")
local act = wezterm.action

return {
	color_scheme = "Molokai",
	tab_bar_at_bottom = true,
	use_fancy_tab_bar = false,

	keys = {
		-- CTRL
		{ key = "phys:Equal", mods = "CTRL", action = act.IncreaseFontSize },
		{ key = "phys:Minus", mods = "CTRL", action = act.DecreaseFontSize },
		{ key = "phys:Insert", mods = "CTRL", action = act.CopyTo("PrimarySelection") },
		{ key = "phys:0", mods = "CTRL", action = act.ResetFontSize },
		{ key = "phys:PageUp", mods = "CTRL", action = act.ActivateTabRelative(-1) },
		{ key = "phys:PageDown", mods = "CTRL", action = act.ActivateTabRelative(1) },
		{ key = "phys:Tab", mods = "CTRL", action = act.ActivateTabRelative(1) },
		-- SHIFT
		{ key = "phys:Insert", mods = "SHIFT", action = act.PasteFrom("PrimarySelection") },
		{ key = "phys:PageUp", mods = "SHIFT", action = act.ScrollByPage(-1) },
		{ key = "phys:PageDown", mods = "SHIFT", action = act.ScrollByPage(1) },
		-- SHIFT-CTRL
		{ key = "phys:1", mods = "SHIFT|CTRL", action = act.ActivateTab(0) },
		{ key = "phys:2", mods = "SHIFT|CTRL", action = act.ActivateTab(1) },
		{ key = "phys:3", mods = "SHIFT|CTRL", action = act.ActivateTab(2) },
		{ key = "phys:4", mods = "SHIFT|CTRL", action = act.ActivateTab(3) },
		{ key = "phys:5", mods = "SHIFT|CTRL", action = act.ActivateTab(4) },
		{ key = "phys:6", mods = "SHIFT|CTRL", action = act.ActivateTab(5) },
		{ key = "phys:7", mods = "SHIFT|CTRL", action = act.ActivateTab(6) },
		{ key = "phys:8", mods = "SHIFT|CTRL", action = act.ActivateTab(7) },
		{ key = "phys:9", mods = "SHIFT|CTRL", action = act.ActivateTab(-1) },
		{ key = "phys:C", mods = "SHIFT|CTRL", action = act.CopyTo("Clipboard") },
		{ key = "phys:Equal", mods = "SHIFT|CTRL", action = act.IncreaseFontSize },
		{ key = "phys:Minus", mods = "SHIFT|CTRL", action = act.DecreaseFontSize },
		{ key = "phys:0", mods = "SHIFT|CTRL", action = act.ResetFontSize },
		{ key = "phys:F", mods = "SHIFT|CTRL", action = act.Search("CurrentSelectionOrEmptyString") },
		{ key = "phys:k", mods = "SHIFT|CTRL", action = act.ClearScrollback("ScrollbackOnly") },
		{ key = "phys:l", mods = "SHIFT|CTRL", action = act.ShowDebugOverlay },
		{ key = "phys:R", mods = "SHIFT|CTRL", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
		{ key = "phys:D", mods = "SHIFT|CTRL", action = act.SplitVertical({ domain = "CurrentPaneDomain" }) },
		{ key = "phys:LeftArrow", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection("Left") },
		{ key = "phys:UpArrow", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection("Up") },
		{ key = "phys:RightArrow", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection("Right") },
		{ key = "phys:DownArrow", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection("Down") },
		{ key = "phys:m", mods = "SHIFT|CTRL", action = act.Hide },
		{ key = "phys:n", mods = "SHIFT|CTRL", action = act.SpawnWindow },
		{ key = "phys:P", mods = "SHIFT|CTRL", action = act.PaneSelect({ alphabet = "", mode = "Activate" }) },
		{ key = "phys:Space", mods = "SHIFT|CTRL", action = act.QuickSelect },
		{ key = "phys:T", mods = "SHIFT|CTRL", action = act.SpawnTab("CurrentPaneDomain") },
		{ key = "phys:Tab", mods = "SHIFT|CTRL", action = act.ActivateTabRelative(-1) },
		{
			key = "phys:u",
			mods = "SHIFT|CTRL",
			action = act.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }),
		},
		{ key = "phys:v", mods = "SHIFT|CTRL", action = act.PasteFrom("Clipboard") },
		{ key = "phys:w", mods = "SHIFT|CTRL", action = act.CloseCurrentTab({ confirm = true }) },
		{ key = "phys:X", mods = "SHIFT|CTRL", action = act.ActivateCopyMode },
		{ key = "phys:Z", mods = "SHIFT|CTRL", action = act.TogglePaneZoomState },
		{ key = "phys:F", mods = "SHIFT|CTRL", action = act.ToggleFullScreen },
		-- SHIFT-ALT-CTRL
		{ key = "phys:LeftArrow", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize({ "Left", 1 }) },
		{ key = "phys:UpArrow", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize({ "Up", 1 }) },
		{ key = "phys:RightArrow", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize({ "Right", 1 }) },
		{ key = "phys:DownArrow", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize({ "Down", 1 }) },
		{ key = "phys:5", mods = "SHIFT|ALT|CTRL", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
		{ key = "phys:Quote", mods = "SHIFT|ALT|CTRL", action = act.SplitVertical({ domain = "CurrentPaneDomain" }) },
		{ key = "phys:R", mods = "SHIFT|ALT|CTRL", action = act.ReloadConfiguration },
		--- ALT-CTRL
		{ key = "phys:LeftArrow", mods = "ALT|CTRL", action = act.AdjustPaneSize({ "Left", 1 }) },
		{ key = "phys:UpArrow", mods = "ALT|CTRL", action = act.AdjustPaneSize({ "Up", 1 }) },
		{ key = "phys:RightArrow", mods = "ALT|CTRL", action = act.AdjustPaneSize({ "Right", 1 }) },
		{ key = "phys:DownArrow", mods = "ALT|CTRL", action = act.AdjustPaneSize({ "Down", 1 }) },
		-- NONE
		{ key = "Copy", mods = "NONE", action = act.CopyTo("Clipboard") },
		{ key = "Paste", mods = "NONE", action = act.PasteFrom("Clipboard") },
	},

	key_tables = {
		copy_mode = {
			{ key = "Tab", mods = "NONE", action = act.CopyMode("MoveForwardWord") },
			{ key = "Tab", mods = "SHIFT", action = act.CopyMode("MoveBackwardWord") },
			{ key = "Enter", mods = "NONE", action = act.CopyMode("MoveToStartOfNextLine") },
			{ key = "Escape", mods = "NONE", action = act.CopyMode("Close") },
			{ key = "Space", mods = "NONE", action = act.CopyMode({ SetSelectionMode = "Cell" }) },
			{ key = "$", mods = "NONE", action = act.CopyMode("MoveToEndOfLineContent") },
			{ key = "$", mods = "SHIFT", action = act.CopyMode("MoveToEndOfLineContent") },
			{ key = "0", mods = "NONE", action = act.CopyMode("MoveToStartOfLine") },
			{ key = "G", mods = "NONE", action = act.CopyMode("MoveToScrollbackBottom") },
			{ key = "G", mods = "SHIFT", action = act.CopyMode("MoveToScrollbackBottom") },
			{ key = "H", mods = "NONE", action = act.CopyMode("MoveToViewportTop") },
			{ key = "H", mods = "SHIFT", action = act.CopyMode("MoveToViewportTop") },
			{ key = "L", mods = "NONE", action = act.CopyMode("MoveToViewportBottom") },
			{ key = "L", mods = "SHIFT", action = act.CopyMode("MoveToViewportBottom") },
			{ key = "M", mods = "NONE", action = act.CopyMode("MoveToViewportMiddle") },
			{ key = "M", mods = "SHIFT", action = act.CopyMode("MoveToViewportMiddle") },
			{ key = "O", mods = "NONE", action = act.CopyMode("MoveToSelectionOtherEndHoriz") },
			{ key = "O", mods = "SHIFT", action = act.CopyMode("MoveToSelectionOtherEndHoriz") },
			{ key = "V", mods = "NONE", action = act.CopyMode({ SetSelectionMode = "Line" }) },
			{ key = "V", mods = "SHIFT", action = act.CopyMode({ SetSelectionMode = "Line" }) },
			{ key = "^", mods = "NONE", action = act.CopyMode("MoveToStartOfLineContent") },
			{ key = "^", mods = "SHIFT", action = act.CopyMode("MoveToStartOfLineContent") },
			{ key = "b", mods = "NONE", action = act.CopyMode("MoveBackwardWord") },
			{ key = "b", mods = "ALT", action = act.CopyMode("MoveBackwardWord") },
			{ key = "b", mods = "CTRL", action = act.CopyMode("PageUp") },
			{ key = "c", mods = "CTRL", action = act.CopyMode("Close") },
			{ key = "f", mods = "ALT", action = act.CopyMode("MoveForwardWord") },
			{ key = "f", mods = "CTRL", action = act.CopyMode("PageDown") },
			{ key = "g", mods = "NONE", action = act.CopyMode("MoveToScrollbackTop") },
			{ key = "g", mods = "CTRL", action = act.CopyMode("Close") },
			{ key = "h", mods = "NONE", action = act.CopyMode("MoveLeft") },
			{ key = "j", mods = "NONE", action = act.CopyMode("MoveDown") },
			{ key = "k", mods = "NONE", action = act.CopyMode("MoveUp") },
			{ key = "l", mods = "NONE", action = act.CopyMode("MoveRight") },
			{ key = "m", mods = "ALT", action = act.CopyMode("MoveToStartOfLineContent") },
			{ key = "o", mods = "NONE", action = act.CopyMode("MoveToSelectionOtherEnd") },
			{ key = "q", mods = "NONE", action = act.CopyMode("Close") },
			{ key = "v", mods = "NONE", action = act.CopyMode({ SetSelectionMode = "Cell" }) },
			{ key = "v", mods = "CTRL", action = act.CopyMode({ SetSelectionMode = "Block" }) },
			{ key = "w", mods = "NONE", action = act.CopyMode("MoveForwardWord") },
			{
				key = "y",
				mods = "NONE",
				action = act.Multiple({ { CopyTo = "ClipboardAndPrimarySelection" }, { CopyMode = "Close" } }),
			},
			{ key = "PageUp", mods = "NONE", action = act.CopyMode("PageUp") },
			{ key = "PageDown", mods = "NONE", action = act.CopyMode("PageDown") },
			{ key = "LeftArrow", mods = "NONE", action = act.CopyMode("MoveLeft") },
			{ key = "LeftArrow", mods = "ALT", action = act.CopyMode("MoveBackwardWord") },
			{ key = "RightArrow", mods = "NONE", action = act.CopyMode("MoveRight") },
			{ key = "RightArrow", mods = "ALT", action = act.CopyMode("MoveForwardWord") },
			{ key = "UpArrow", mods = "NONE", action = act.CopyMode("MoveUp") },
			{ key = "DownArrow", mods = "NONE", action = act.CopyMode("MoveDown") },
		},

		search_mode = {
			{ key = "Enter", mods = "NONE", action = act.CopyMode("PriorMatch") },
			{ key = "Escape", mods = "NONE", action = act.CopyMode("Close") },
			{ key = "n", mods = "CTRL", action = act.CopyMode("NextMatch") },
			{ key = "p", mods = "CTRL", action = act.CopyMode("PriorMatch") },
			{ key = "r", mods = "CTRL", action = act.CopyMode("CycleMatchType") },
			{ key = "u", mods = "CTRL", action = act.CopyMode("ClearPattern") },
			{ key = "PageUp", mods = "NONE", action = act.CopyMode("PriorMatchPage") },
			{ key = "PageDown", mods = "NONE", action = act.CopyMode("NextMatchPage") },
			{ key = "UpArrow", mods = "NONE", action = act.CopyMode("PriorMatch") },
			{ key = "DownArrow", mods = "NONE", action = act.CopyMode("NextMatch") },
		},
	},
}
